# Configuration Media Service
s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin123}
  region: ${S3_REGION:us-east-1}
  bucket:
    avatars: avatars
    images: images
    audio: audio
    video: video
    temp: temp

media:
  max-file-size:
    image: 10485760      # 10 MB
    audio: 52428800      # 50 MB
    video: 209715200     # 200 MB
  thumbnail:
    size: 256            # 256x256 pixels
  temp-file-expiration: 24 # heures
